In [1]:
import tensorflow as tf

print(tf.__version__) 

1.15.0


In [2]:
# 상수 정의
a = tf.constant(1234)
b = tf.constant(5000)

In [3]:
# 계산 정의
add_op = a+b

In [4]:
# 세션 시작
sess = tf.Session()
res = sess.run(add_op) # 계산식 평가
print(res)

6234


In [5]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

# 계산 정의
calc1_op = a+b*c
calc2_op = (a+b)*c

# 세션 시작
sess = tf.Session()
res1 = sess.run(calc1_op)
print(res1)
res2 = sess.run(calc2_op)
print(res2)

14
20


In [6]:
# 이렇게 하면 오류남(변수 초기화 선언 안해서)

a = tf.constant(100)
b = tf.constant(50)
add_op = a+b

# 변수 v 선언하기
v = tf.Variable(10)

# 세션 시작
sess = tf.Session()

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)

# 세션 시작
sess = tf.Session()

print(sess.run(v))

# 계산식 실행
sess.run(let_op)
print(sess.run(v))

FailedPreconditionError: Attempting to use uninitialized value Variable
	 [[{{node _retval_Variable_0_0}}]]

In [7]:
a = tf.constant(100)
b = tf.constant(50)
add_op = a+b

# 변수 v 선언하기
v = tf.Variable(10)

# 세션 시작
sess = tf.Session()

# 변수 v에 add_op의 결과 대입하기
let_op = tf.assign(v, add_op)

#변수 초기화하기
sess.run(tf.global_variables_initializer())

# 계산식 실행
print(sess.run(v))
sess.run(let_op)
print(sess.run(v))

10
150


In [8]:
# placeholder 정의(정수 자료형 3개를 가진 배열)
a = tf.placeholder(tf.int32, [3])
b = tf.constant(2)
x2_op = a*b

# 세션 시작
sess = tf.Session()
# placeholder에 값 넣고 실행하기
r1 = sess.run(x2_op, feed_dict = {a:[1,2,3]})
print(r1)
r2 = sess.run(x2_op, feed_dict = {a:[10,20,10]})
print(r2)

[2 4 6]
[20 40 20]


- tensoflow.sqrt(x): x의 제곱근을 계산
- tensoflow.reduce_mean(x): x의 평균을 계산
- tensoflow.square(x): x의 제곱을 계산
- random_uniform([1], 0, 10,…) : 0에서 10 사이에서 임의의 수 1개 생성 반환
- Variable() : 변수의 값을 지정 

In [9]:
# placeholder 정의(배열의 크기를 None으로 지정)
a = tf.placeholder(tf.int32, [None])
b = tf.constant(10)
x10_op = a*b

#세션 시작
ses = tf.Session()

#placeholder에 값 넣고 실행하기
r1 = sess.run(x10_op, feed_dict = {a:[1,2,3,4,5]})
print(r1)
r2 = sess.run(x10_op, feed_dict = {a:[10,20]})
print(r2)

[10 20 30 40 50]
[100 200]


---------

- SVM으로 BMI 판정
- 키의 최대값은 200cm, 몸무게의 최대값은 100kg으로 정규화
- 저체중(thin), 정상(normal), 비만(fat) 레이블을 one-hot-encoding [1, 0, 0], [0, 1, 0], [0, 0, 1]로 변환
- 소프트 맥스 회귀방법 , 오차 함수는 교차 엔트로피 사용
- 교차 엔트로피  - 2개의 확률 분포 사이에 정의되는 척도로서 교차 엔트로피 값이 작을 수록 정확한 값을 냄
- 학습 계수 0.01, 경사 하강법(steepest descent method) 사용

In [10]:
# import pandas as pd
# import numpy as np
# import tensorflow as tf

# # 키, 몸무게, 레이블이 적힌 CSV파일 읽어 들이기
# csv = pd.read_csv("bmi.csv")

# # 데이터 정규화
# csv["height"] = csv["height"]/200
# csv["weight"] = csv["weight"]/100

# # 레이블을 배열로 변환하기 - thin=(1,0,0) / normal = (0,1,0) / fat = (0,0,1)

# # 테스트를 위한 데이터 분리

# # 데이터 플로우 그래프 구축하기

# # 플레이스홀더 선언하기
# x = tf.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기
# y_ = tf.placeholder(tf.float32, [None, 3]) # 정답 레이블 넣기

# # 

In [11]:
import tensorflow as tf
# 데이터 플로우 그래프 구축하기  
a = tf.constant(20, name="a")
b = tf.constant(30, name="b")
mul_op = a * b
# 세션 생성하기  
sess = tf.Session()
# TensorBoard 사용하기  
tw = tf.summary.FileWriter("log_dir", graph=sess.graph)
# 세션 실행하기 
print(sess.run(mul_op))

600
